buildLibrary parallelization & better lucode2 auto-update
pik-piam/lucode2 pull request #132
Opened 2022-10-31 12:39 UTC by pfuehrlich-pik

This PR introduces parallelization to lucode2::check (which is where buildLibrary spends most of the time): There are 3 background processes (started via `callr::r_bg`) running in parallel, one each for tests, linter, and checks. As soon as there is an error in any process all processes are killed and the error is reported.

The second feature introduced is an auto update if there's a lucode2 update available. Right after installing the update, a new R session is started via `callr::r` which runs buildLibrary with the updated version of lucode2. A restart of the R session after installing a lucode2 update is thus no longer necessary.

some small stuff:
- removed 2 very simple examples because they were taking > 5s during buildLibrary
- some smaller functions were split out of buildLibrary to reduce cyclomatic complexity
- `getLine` is now used everywhere in lucode2
- bugfix for checkRepoUpToDate when running without internet

2022-11-01 08:21 UTC, mikapfl approved these changes

2022-11-01 08:21 UTC, mikapfl commented on R/buildLibrary.R
> +    # getLine and similar functions don't work everywhere via callr, so must ask questions before this
>  `# getLine and similar functions don't work everywhere via callr, so must ask questions before this`

that's sad. `system` would work, wouldn't it? (Not necessarily advocating `system`, but still kinda sad if another solution loses features compared to `system`)

2022-11-01 08:34 UTC, pfuehrlich-pik commented on R/buildLibrary.R
> +    # getLine and similar functions don't work everywhere via callr, so must ask questions before this
I'm not sure, RStudio is doing some weird things with stdin. I just tried `system2("head", "-1")`, which should get a line from the user and just print it, but in RStudio it doesn't.

2022-11-01 08:37 UTC, pfuehrlich-pik commented on R/buildLibrary.R
> +    # getLine and similar functions don't work everywhere via callr, so must ask questions before this
In VSCode and Ubuntu bash terminal the following works: `callr::r(function() readLines(withr::local_connection(file("stdin")), n = 1), stdin = "")`, but not in RStudio (I didn't check jupyter).

2022-11-01 08:41 UTC, pfuehrlich-pik commented on R/buildLibrary.R
> +    # getLine and similar functions don't work everywhere via callr, so must ask questions before this
`?stdin`
> stdin() refers to the ‘console’ and not to the C-level ‘stdin’ of the process. The distinction matters in GUI consoles (which may not have an active ‘stdin’, and if they do it may not be connected to console input), and also in embedded applications. If you want access to the C-level file stream ‘stdin’, use [file](https://github.com/pik-piam/lucode2/help/file.html)("stdin")

2022-11-01 09:11 UTC, tscheypidi requested changes

2022-11-01 09:11 UTC, tscheypidi commented on R/buildLibrary.R
> +  updateType <- handleUpdateType(updateType)
I am not so sure whether this is a good idea to put it here. In particular it would be unclear to me what that means if a build fails. Does that mean that I have to do the same choice next time or do I have to select "no version increment" then? I can imagine that this leads to incorrect choices here (either multiple version bumps at once or no version increment at all)

2022-11-01 09:11 UTC, tscheypidi commented on R/buildLibrary.R
> +  if (outdatedLucode2Loaded) {
why don't you put the check directly in the if-statement?

2022-11-01 09:13 UTC, pfuehrlich-pik commented on R/buildLibrary.R
> +    # getLine and similar functions don't work everywhere via callr, so must ask questions before this
An R session inside RStudio's "Terminal" seems to work just like VSCode also, just not the R "Console" :see_no_evil: I did some more research and found some other people having similar problems, I'm pretty sure this cannot be fixed without considerable effort.

2022-11-01 09:16 UTC, pfuehrlich-pik commented on R/buildLibrary.R
> +  updateType <- handleUpdateType(updateType)
I agree. The problem is we need to do all the interaction before starting the new R session via callr. I guess we could only ask early if the callr session is used, and ask late otherwise (like before). Would that be ok?

2022-11-01 09:17 UTC, pfuehrlich-pik commented on R/buildLibrary.R
> +  if (outdatedLucode2Loaded) {
Sometimes I do this to give a name to a check, but the comment explains what's going on here, I'll change it

2022-11-01 10:11 UTC, mikapfl commented on R/buildLibrary.R
> +  updateType <- handleUpdateType(updateType)
What is the problem? The first time I run this, I select whatever is appropriate if the build succeeds. Then, my build fails. The next time I run it, it asks again, and I either
* Say "no increment" because I know the version was incremented already, that's fine
* Say "increment again" because I forgot, that's fine as well, version numbers are free, no harm done.

Am I missing something?

2022-11-01 10:16 UTC, mikapfl commented on R/buildLibrary.R
> +  updateType <- handleUpdateType(updateType)
It is fundamentally the same as any time I amend a PR, so the workflow
1. Commit something useful
2. Do a successful buildLibrary, commit it
3. Commit some other useful thing
4. Do another buildLibrary, now not incrementing version numbers (or incrementing them twice)

2022-11-01 11:23 UTC, tscheypidi commented on R/buildLibrary.R
> +  updateType <- handleUpdateType(updateType)
I agree that this workflow allows you to update it properly, but I think the workflow invites/encourages incorrect usage much more and I think experience showed in the past that this kind of misuse will happen. I think for a user which does not know the details about the function as we know it it might be rather unclear what the correct selection is here

@pfuehrlich-pik is it possible to do the increment after the parallel sessions finished (back in the main session)?

2022-11-01 12:38 UTC, mikapfl commented on R/buildLibrary.R
> +  updateType <- handleUpdateType(updateType)
I also argue that we shouldn't try to stop "incorrect" usages because version numbers are free and properly stopping incorrect usages introduces considerable complexity (e.g. comparing upstream develop and the current state to determine if the version number was increased already)

2022-11-01 12:59 UTC, tscheypidi commented on R/buildLibrary.R
> +  updateType <- handleUpdateType(updateType)
It is not about stopping incorrect usage, it is about encouraging it or not. Having the version increment at the end of the line still allows you to change the number as you like, but it makes it less likely that version numbers are changed differently by the user than actually intended

2022-11-01 13:19 UTC, pfuehrlich-pik commented on R/buildLibrary.R
> +  updateType <- handleUpdateType(updateType)
I think asking after the callr session should work, I'll try to implement that

2022-11-02 14:47 UTC, tscheypidi approved these changes

2022-11-02 14:52 UTC, merged