check for updates in buildLibrary, new always added GitHub Action, remove travis related code
pik-piam/lucode2 pull request #36
Opened 2021-09-14 19:26 UTC by pfuehrlich-pik

- when running buildLibrary with an outdated version the update process will be triggered and buildLibrary will stop
- there's a new `lucode2::check` function which runs checks and tests using the accepted warnings/notes logic; buildLibrary is running `lucode2::check`
- there's a new GitHub Action using `r-lib/actions/setup-r-dependencies@v1` and `lucode2::check`
- GitHub Actions are now always activated, UseGithubActions config is removed
- travis related code was removed

2021-09-21 15:52 UTC, tscheypidi requested changes

2021-09-21 15:52 UTC, tscheypidi commented on R/buildLibrary.R
> +  pleaseRestartSession <- paste("Please restart your R session (in RStudio: Ctrl+Shift+F10) to make sure that the",
There should be a possibility implemented which allows to run buildLibrary in an older version as otherwise we might run into a situation in which the the whol building process collapses (e.g. if the newest version of lucode2 for some reason does not work for the user). You could add for instance an argument `checkForUpdates` which is by default set to `TRUE` but could be set to `FALSE` if necessary

2021-09-21 15:52 UTC, tscheypidi commented on README.md
> +R package **lucode2**, version **1.0.0**
version increment to 1.0.0?

2021-09-21 15:52 UTC, tscheypidi commented on tests/testthat/test-checkRequiredPackages.R
> +  requireNamespace("waldo", quietly = TRUE) # load waldo package needed for expect_false before setting .libPaths
I don't get that one. What is this required for?

2021-09-21 17:48 UTC, pfuehrlich-pik commented on tests/testthat/test-checkRequiredPackages.R
> +  requireNamespace("waldo", quietly = TRUE) # load waldo package needed for expect_false before setting .libPaths
This is of course pretty fragile, if `testthat` is switching from `waldo` to another package the test will probably break. I'm happy about any suggestions how to improve this

2021-09-22 07:05 UTC, tscheypidi commented on tests/testthat/test-checkRequiredPackages.R
> +  requireNamespace("waldo", quietly = TRUE) # load waldo package needed for expect_false before setting .libPaths
sounds dangerous.....is that behavior the same for `expect_true`? If not, that might be a workaround

2021-09-22 07:21 UTC, pfuehrlich-pik commented on README.md
> +R package **lucode2**, version **1.0.0**
There are not breaking changes, but I feel there's enough happening to justify a major version. Also, version <1.0.0 always seem to me like they're still in beta. I don't have strong feelings about this though, I do a minor version increment if you want.

2021-09-22 07:24 UTC, pfuehrlich-pik commented on tests/testthat/test-checkRequiredPackages.R
> +  requireNamespace("waldo", quietly = TRUE) # load waldo package needed for expect_false before setting .libPaths
`expect_true` works in the same way. Maybe I can put the `expect_false` statements after resetting the `.libPaths`, I'll try that.

2021-09-22 07:46 UTC, tscheypidi commented on README.md
> +R package **lucode2**, version **1.0.0**
I would be in favor of having a minor version increment. I agree that "beta" is probably not the right description of the package status, but on the other hand behavior of some functions still might change considerably. So, indicating this potentially unstable API might be good

2021-09-22 08:48 UTC, pfuehrlich-pik commented on tests/testthat/test-checkRequiredPackages.R
> +  requireNamespace("waldo", quietly = TRUE) # load waldo package needed for expect_false before setting .libPaths
I reworked the test, now it's no longer messing with .libPaths, please take another look.

2021-09-22 09:02 UTC, tscheypidi approved these changes

2021-09-22 09:04 UTC, merged