Add support for custom content in README.md
pik-piam/lucode2 pull request #43
Opened 2021-10-28 15:50 UTC by tscheypidi

-added possibility to add custom content to autocreated README.md in package2readme and buildLibrary
- added description of available settings in .buildLibrary config file

2021-10-29 19:15 UTC, tscheypidi commented on R/package2readme.R
> +#' 1) a line of markdown code, 2) a path to a markdown file, or 3) a path to a Rmarkdown file
I share your opinion on the issues of too much flexibility, but applied on this particular case I disagree. The reason is that md support what in my opinion cut here a bit too short as there are reasonable examples out there why one would want to use Rmd over md. And as soon as Rmd is set as supported format the other options follow automatically with only very little extra code.

2021-10-29 19:15 UTC, tscheypidi commented on R/package2readme.R
> +    for (a in add) {
;)

2021-11-01 11:18 UTC, pfuehrlich-pik requested changes
`fType` has to be renamed everywhere

2021-11-01 11:18 UTC, pfuehrlich-pik commented on R/package2readme.R
>          if (tolower(fType) == "rmd") {
`fType` needs to be renamed everywhere, not sure if this is the only place.
```suggestion
        if (tolower(fileType) == "rmd") {
```

2021-11-01 11:18 UTC, pfuehrlich-pik commented on R/package2readme.R
> +          tmpFile <- withr::local_tempfile()
Maybe use `#' @importFrom withr local_tempfile` instead of `::`?

2021-11-01 11:18 UTC, pfuehrlich-pik commented on R/package2readme.R
> +        fileType <- tools::file_ext(a)
Does buildLibrary still run with this, or do we need to add tools as a dependency in `DESCRIPTION`? I'd also probably use `#' @importFrom tools file_ext` instead of `::`

2021-11-01 11:25 UTC, pfuehrlich-pik approved these changes

2021-11-01 12:12 UTC, merged